language: node_js

env:
  - DATABASE_URL=postgresql://yongama:pg123@localhost:5432/registration

node_js:
  - "12.18.3"

before_script:
  - psql -c 'create database  table;' -U postgres
  - psql -U postgres -d table -a -f table.sql

services:
  - postgresql
